Repository softwaredelta/GNP, pull requests merged in 2023-06, with the labels that each got.

#312 [FRONT] Fixed bugs from url image
  ram-front/src/components/forms/EditDeliveryForm.tsx
  ram-front/src/components/forms/ModalDeliveryFormCreate.tsx
  ram-front/src/components/prospects/ListProspects.tsx
  ram-front/src/components/tables/SearchDeliveryRow.tsx
  ram-front/src/pages/Members.tsx
  ram-front/src/types/index.ts
Labels: bug

#316 [FRONT] Fixes on Links, PP200 Button and Removed Console Logs
  ram-front/src/components/forms/ProfileForm.tsx
  ram-front/src/components/generics/lists/LinkList.tsx
  ram-front/src/components/generics/lists/LinkRow.tsx
  ram-front/src/components/prospects/FunnelRow.tsx
  ram-front/src/components/prospects/FunnelTable.tsx
Labels: WEB

#323 301 front agent sales view can´t re render
  ram-back/src/controller/sale.ts
  ram-front/src/__test__/newsale.test.tsx
  ram-front/src/__test__/saleshistory.test.tsx
  ram-front/src/components/sales/SalesRow.tsx
  ram-front/src/components/sales/SalesTable.tsx
  ram-front/src/lib/api/api-assurance-type.tsx
  ram-front/src/lib/api/api-prospect.tsx
  ram-front/src/lib/api/api-sales.ts
  ram-front/src/pages/ModifySale.tsx
  ram-front/src/pages/NewSale.tsx
  ram-front/src/pages/SalesHistory.tsx
Labels: bug, defectlog

#325 309 front standarization of buttons
  ram-front/src/components/BackButton.tsx
  ram-front/src/components/auth/LoginForm.tsx
  ram-front/src/components/deliverables/ListManagerDeliveries.tsx
  ram-front/src/components/deliverables/UserDeliveriesTable.tsx
  ram-front/src/components/deliverables/UserDeliveryRow.tsx
  ram-front/src/components/forms/EditDeliveryForm.tsx
  ram-front/src/components/forms/ModalAddUser.tsx
  ram-front/src/components/forms/ModalDeliveryFormCreate.tsx
  ram-front/src/components/forms/ModalDeliveryFormUpdate.tsx
  ram-front/src/components/forms/ModalPasswordReset.tsx
  ram-front/src/components/forms/ModalProspectForm.tsx
  ram-front/src/components/forms/ProfileForm.tsx
  ram-front/src/components/forms/SaleForm.tsx
  ram-front/src/components/forms/UserForm.tsx
  ram-front/src/components/generics/alerts/Alert.tsx
  ram-front/src/components/generics/cards/ProfileCard.tsx
  ram-front/src/components/generics/cards/info/CardInfoNumMembers.tsx
  ram-front/src/components/generics/cards/info/ManagerDelivery.tsx
  ram-front/src/components/generics/lists/LinkDeliveryList.tsx
  ram-front/src/components/generics/lists/LinkList.tsx
  ram-front/src/components/generics/lists/LinkRow.tsx
  ram-front/src/components/includes/NavBar/NavBar.tsx
  ram-front/src/components/members/RowMember.tsx
  ram-front/src/components/prospects/RowProspect.tsx
  ram-front/src/components/sales/SalesFilters.tsx
  ram-front/src/components/sales/SalesRow.tsx
  ram-front/src/components/sales/VerifySalesRow.tsx
  ram-front/src/components/tables/SearchAgentRow.tsx
  ram-front/src/components/tables/SearchAgentTable.tsx
  ram-front/src/components/tables/SearchDeliveryRow.tsx
  ram-front/src/pages/AddUser.tsx
  ram-front/src/pages/DeliveryGroup.tsx
  ram-front/src/pages/EditGroup.tsx
  ram-front/src/pages/ManagerDelivery.tsx
  ram-front/src/pages/ManagerGroups.tsx
  ram-front/src/pages/Members.tsx
  ram-front/src/pages/ModifySale.tsx
  ram-front/src/pages/NewSale.tsx
  ram-front/src/pages/Profile.tsx
  ram-front/src/pages/Prospects.tsx
  ram-front/src/pages/TODO/MySalesMetrics.tsx
  ram-front/src/routes/privates.tsx
Labels: bug, enhancement, defectlog

#343 [FRONT] Fixed re-render bugs
  ram-front/src/components/deliverables/UserDeliveriesTable.tsx
  ram-front/src/components/deliverables/UserDeliveryRow.tsx
  ram-front/src/components/forms/EditDeliveryForm.tsx
  ram-front/src/components/forms/ModalGroupForm.tsx
  ram-front/src/components/sales/VerifySalesRow.tsx
  ram-front/src/pages/EditGroup.tsx
  ram-front/src/pages/ManagerDelivery.tsx
  ram-front/src/pages/ManagerDeliveryGroup.tsx
  ram-front/src/pages/ManagerGroups.tsx
Labels: bug, defectlog

#347 [FRONT] [BACK] Add delete function for members
  ram-back/src/app/user.ts
  ram-back/src/controller/user.ts
  ram-front/src/components/members/RowMember.tsx
  ram-front/src/components/members/TableMembers.tsx
  ram-front/src/pages/Members.tsx
Labels: 🐂 Medium, 🏕 Medium

#351 [FRONT] Added cell for agent name in verifySalesTable
  ram-front/src/components/sales/VerifySalesRow.tsx
  ram-front/src/components/sales/VerifySalesTable.tsx
Labels: 🦔 Tiny, defectlog

#355 352 front when modifying the user it is not changed in the navbar without a refresh and it does not appear well in the avatar component either
  ram-front/src/components/forms/ProfileForm.tsx
  ram-front/src/pages/Profile.tsx
  ram-front/src/routes/privates.tsx
Labels: 🦔 Tiny

#361 358 front back m4 s02 see progress and metrics in groups of an agent
  ram-back/src/app/groups.ts
  ram-back/src/controller/group.ts
  ram-front/src/components/generics/ProgressBar.tsx
  ram-front/src/components/members/RowMember.tsx
  ram-front/src/components/metrics/GroupProgress.tsx
  ram-front/src/pages/Metrics.tsx
  ram-front/src/routes/privates.tsx
Labels: 🐂 Medium, 🏕 Medium

#367 348 front integration with highcharts
  ram-back/src/app/sale.ts
  ram-back/src/controller/sale.ts
  ram-back/src/seeds/index.ts
  ram-front/package.json
  ram-front/src/components/graphs/LineGraph.tsx
  ram-front/src/pages/Metrics.tsx
  ram-front/yarn.lock
Labels: WEB, 🦑 Large

#374 [FRONT] Added swal for adding an agent in a group
  ram-front/src/components/agent/AgentFuzzyFinder.tsx
Labels: 🦔 Tiny

#385 [FRONT] Added validation for password for 8-characters at least
  ram-front/src/components/forms/ModalPasswordReset.tsx
Labels: defectlog

#404 [FRONT] Fixed progress bar bug
  ram-front/src/components/metrics/GroupProgress.tsx
Labels: bug

#407 [FRONT] Fix numeric parsing as string in Metrics.tsx
  ram-front/src/pages/Metrics.tsx
Labels: WEB, 🦔 Tiny, 🏔 High, defectlog

#413 [BACK] Modified Controller for Prospect Chart
  ram-back/src/controller/status-prospect.ts
Labels: API

#353 [BACK] test for delete user
  ram-back/src/__tests__/app/user.test.ts
  ram-back/src/__tests__/controller/user.test.ts
Labels: API
