Repository softwaredelta/GNP, pull requests merged in 2023-04, with the labels that each got.

#9 [REPO] Removed unusued .idea folder.
  .idea/.gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/discord.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/prettier.xml
  .idea/vcs.xml
Labels: enhancement, 🦔 Tiny, 🏕 Medium

#27 [BACKEND] Add database entities as TypeOrm classes
  ram-back/src/__tests__/arch.test.ts
  ram-back/src/__tests__/groups.test.ts
  ram-back/src/__tests__/user.test.ts
  ram-back/src/app/groups.ts
  ram-back/src/arch/db-client.ts
  ram-back/src/entities/assurance-type.entity.ts
  ram-back/src/entities/columns.ts
  ram-back/src/entities/delivery.entity.ts
  ram-back/src/entities/goal.entity.ts
  ram-back/src/entities/group-user.entity.ts
  ram-back/src/entities/group.entity.ts
  ram-back/src/entities/index.ts
  ram-back/src/entities/module.entity.ts
  ram-back/src/entities/origin.entity.ts
  ram-back/src/entities/role.entity.ts
  ram-back/src/entities/sell.entity.ts
  ram-back/src/entities/state.entity.ts
  ram-back/src/entities/user-delivery.ts
  ram-back/src/entities/user-level.entity.ts
  ram-back/src/entities/user.entity.ts
  ram-back/src/seeds/index.ts
  ram-back/tsconfig.json
Labels: API

#60 34 m1 s04gerentever cursos y número de agentes por grupo
  ram-back/src/controller/group.ts
  ram-back/src/controller/routes.ts
  ram-back/src/seeds/index.ts
  ram-front/package.json
  ram-front/src/components/generics/cards/info/CardInfoNumMembers.tsx
  ram-front/src/lib/api/api-courses.ts
  ram-front/src/pages/Home.tsx
  ram-front/src/pages/ManagerCourses.tsx
Labels: 🐂 Medium, 🏕 Medium

#70 [Auth] Show bad login alert on page
  ram-front/index.html
  ram-front/src/components/auth/Login.tsx
  ram-front/src/components/auth/LoginForm.tsx
  ram-front/src/components/generics/alerts/Alert.tsx
  ram-front/src/hooks/useAlert.ts
  ram-front/src/lib/api/api-auth.tsx
  ram-front/src/pages/Login.tsx
  ram-front/src/pages/index.tsx
  ram-front/src/recoil/visual/atoms.ts
  ram-front/src/recoil/visual/index.ts
  ram-front/src/recoil/visual/selectors.ts
Labels: WEB

#67 [Front] Make sure we use react router links
  ram-front/src/components/includes/NavBar/NavBar.tsx
  ram-front/src/pages/Home.tsx
Labels: WEB

#79 [Fix] POST for NewSale was fixed
  ram-back/src/__tests__/app/sale.test.ts
  ram-back/src/__tests__/controller/sale.test.ts
  ram-back/src/app/sale.ts
  ram-back/src/controller/sale.ts
  ram-back/src/seeds/index.ts
  ram-front/src/pages/Home.tsx
  ram-front/src/routes/privates.ts
Labels: bug

#87 [Back] Fix peer dependencies
  ram-back/package.json
  ram-back/yarn.lock
Labels: API

#84 69 m1 s06gerentever lista de agentes que han hecho un entregable específico
  ram-back/src/__tests__/controller/deliveries.test.ts
  ram-back/src/__tests__/controller/delivery.test.ts
  ram-back/src/app/deliveries.ts
  ram-back/src/app/user.ts
  ram-back/src/controller/assuranceType.ts
  ram-back/src/controller/delivery.ts
  ram-back/src/controller/group.ts
  ram-back/src/controller/sale.ts
  ram-back/src/entities/delivery.entity.ts
  ram-back/src/entities/group.entity.ts
  ram-back/src/entities/user.entity.ts
  ram-back/src/seeds/index.ts
  ram-front/src/__test__/listDeliveries.test.tsx
  ram-front/src/__test__/listGroups.test.tsx
  ram-front/src/__test__/managerCourses.test.tsx
  ram-front/src/__test__/managerDeliveries.test.tsx
  ram-front/src/components/deliverables/ListDeliverables.tsx
  ram-front/src/components/deliverables/ListManagerDeliveries.tsx
  ram-front/src/components/deliverables/UserDeliveriesTable.tsx
  ram-front/src/components/deliverables/UserDeliveryRow.tsx
  ram-front/src/components/generics/CarouselCard.tsx
  ram-front/src/components/generics/Examples.tsx
  ram-front/src/components/generics/cards/DeliveryCard.tsx
  ram-front/src/components/generics/cards/base/Card.tsx
  ram-front/src/components/generics/cards/base/DeliveryCard.tsx
  ram-front/src/components/generics/cards/info/AgentDelivery.tsx
  ram-front/src/components/generics/cards/info/CardInfoAssurence.tsx
  ram-front/src/components/generics/cards/info/CardInfoTopFive.tsx
  ram-front/src/components/generics/cards/info/ManagerDelivery.tsx
  ram-front/src/components/groups/ListGroup.tsx
  ram-front/src/components/groups/ListManagerGroup.tsx
  ram-front/src/components/groups/ManagerListGroups.tsx
  ram-front/src/components/includes/NavBar/NavBar.tsx
  ram-front/src/components/sales/CardNewSale.tsx
  ram-front/src/components/sales/SalesFilters.tsx
  ram-front/src/components/sales/SalesTable.tsx
  ram-front/src/lib/api/api-assurance-type.tsx
  ram-front/src/lib/api/api-auth.tsx
  ram-front/src/lib/api/api-courses.ts
  ram-front/src/lib/api/api-sales.ts
  ram-front/src/pages/Group.tsx
  ram-front/src/pages/Groups.tsx
  ram-front/src/pages/Home.tsx
  ram-front/src/pages/ManagerDelivery.tsx
  ram-front/src/pages/ManagerGroup.tsx
  ram-front/src/pages/ManagerGroups.tsx
  ram-front/src/pages/NewSale.tsx
  ram-front/src/pages/SalesHistory.tsx
  ram-front/src/pages/index.tsx
  ram-front/src/routes/privates.tsx
  ram-front/src/types/index.ts
Labels: 🏕 Medium

#93 31 m2 s04gerenteverificar venta de un agente
  ram-back/src/__tests__/controller/sale.test.ts
  ram-back/src/app/sale.ts
  ram-back/src/controller/sale.ts
  ram-back/src/seeds/index.ts
  ram-front/src/__test__/verifySales.test.tsx
  ram-front/src/components/sales/VerifySalesRow.tsx
  ram-front/src/components/sales/VerifySalesTable.tsx
  ram-front/src/hooks/useAxios.ts
  ram-front/src/lib/api/api-sales.ts
  ram-front/src/pages/VerifySales.tsx
  ram-front/src/routes/privates.tsx
Labels: API, WEB, 🏕 Medium
