Repository softwaredelta/GNP, pull requests merged in 2023-05, with the labels that each got.

#55 29 m1 s03 subir un entregable
  ram-back/.eslintrc
  ram-back/src/app/user-delivery.ts
  ram-back/src/arch/db-client.ts
  ram-back/src/controller/infra.ts
  ram-back/src/controller/routes.ts
  ram-back/src/controller/user-delivery.ts
  ram-front/index.html
  ram-front/public/RAM.svg
  ram-front/public/favicon-32x32.png
  ram-front/src/__test__/listDeliveries.test.tsx
  ram-front/src/components/Delivery.tsx
  ram-front/src/components/button.tsx
  ram-front/src/components/deliverables/ListDeliverables.tsx
  ram-front/src/components/deliverables/ListManagerDeliveries.tsx
  ram-front/src/components/generics/DropZone.tsx
  ram-front/src/components/generics/Examples.tsx
  ram-front/src/components/generics/cards/DeliveryCard.tsx
  ram-front/src/components/generics/cards/base/DeliveryCard.tsx
  ram-front/src/hooks/useAxios.ts
  ram-front/src/lib/api/api-user-deliveries.ts
  ram-front/src/pages/Group.tsx
  ram-front/src/pages/ManagerDelivery.tsx
Labels: API, WEB, 🐂 Medium, 🏕 Medium

#117 [Infra] Add staging deployment pipeline, fix build pipelines
  .github/workflows/back-ci.yml
  .github/workflows/front-ci.yml
  .github/workflows/staging-deployment.yml
  .gitignore
  fly.toml
  ram-back/jest.config.js
  ram-back/src/arch/db-client.ts
  ram-back/src/arch/s3-client.ts
  ram-back/src/seeds/index.ts
  ram-back/tsconfig.json
  ram-front/src/__test__/ManagerListGroupDeliveries.test.tsx
  ram-front/src/__test__/listDeliveries.test.tsx
  ram-front/src/__test__/managerDeliveries.test.tsx
  ram-front/src/components/Delivery.tsx
  ram-front/src/components/deliverables/ListDeliverables.tsx
  ram-front/src/components/deliverables/UserDeliveryRow.tsx
  ram-front/src/components/generics/Examples.tsx
  ram-front/src/components/generics/cards/DeliveryCard.tsx
  ram-front/src/components/sales/VerifySalesRow.tsx
  ram-front/src/lib/api/api-sales.ts
  ram-front/src/lib/api/api-user-deliveries.ts
  ram-front/src/lib/files.ts
  ram-front/src/types/index.ts
  ram-infra/Dockerfile
  ram-infra/db-setup.sh
  ram-infra/pg_hba.conf
  ram-infra/postgresql.conf
  ram-infra/supervisord.conf
  ram-infra/supervisord.remote.conf
Labels: Infra

#126 M1 s09 modal crear grupo
  ram-front/public/default.jfif
  ram-front/src/assets/css/index.css
  ram-front/src/components/forms/ModalGroupForm.tsx
  ram-front/src/components/generics/Modal.tsx
  ram-front/src/containers/Layout.tsx
  ram-front/src/hooks/usePreviewImage.ts
  ram-front/src/pages/Examples.tsx
  ram-front/src/routes/privates.tsx
  ram-front/tailwind.config.cjs
Labels: WEB, 🐇 Small, 🏕 Medium

#119 [BACK] Created Prospect and related entities
  ram-back/src/entities/prospect-status.entity.ts
  ram-back/src/entities/prospect.entity.ts
  ram-back/src/entities/status.entity.ts
Labels: API, 🐇 Small, 🏕 Medium

#132 [M1 S09 t100] Implement create group endpoint
  ram-back/src/__tests__/app/groups.test.ts
  ram-back/src/__tests__/controller/groups.test.ts
  ram-back/src/app/groups.ts
  ram-back/src/arch/s3-client.ts
  ram-back/src/controller/group.ts
  ram-back/src/entities/group.entity.ts
Labels: API, 🐂 Medium

#135 [Infra] Make linter stricter for unused variables
  ram-back/.eslintrc
  ram-back/src/__tests__/controller/deliveries.test.ts
  ram-back/src/__tests__/controller/delivery.test.ts
  ram-back/src/app/user-delivery.ts
  ram-back/src/controller/files.ts
  ram-back/src/seeds/index.ts
  ram-front/.eslintrc
  ram-front/src/components/Delivery.tsx
  ram-front/src/components/deliverables/ListDeliverables.tsx
  ram-front/src/components/sales/CardNewSale.tsx
  ram-front/src/components/sales/SalesRow.tsx
  ram-front/src/components/sales/VerifySalesRow.tsx
  ram-front/src/components/sales/VerifySalesTable.tsx
  ram-front/src/lib/api/api-auth.tsx
  ram-front/src/pages/Group.tsx
  ram-front/src/pages/SalesHistory.tsx
  ram-front/src/pages/VerifySales.tsx
  ram-front/src/routes/privates.tsx
Labels: 🦑 Large, 🏕 Medium, Infra

#137 M1_S11 New Endpoint for Creating Deliveries and Add Delivery Component
  ram-back/src/controller/delivery.ts
  ram-front/src/assets/css/index.css
  ram-front/src/components/Delivery.tsx
  ram-front/src/components/forms/ModalDeliveryForm.tsx
  ram-front/src/pages/Examples.tsx
  ram-front/tailwind.config.cjs
Labels: API, WEB, 🐂 Medium

#141 136 front add the missing fields to the sale registration form component id3600
  ram-back/src/__tests__/controller/sale.test.ts
  ram-back/src/app/file.ts
  ram-back/src/app/groups.ts
  ram-back/src/controller/sale.ts
  ram-back/src/controller/user-delivery.ts
  ram-front/src/components/sales/CardNewSale.tsx
Labels: API, 🐂 Medium, 🏕 Medium

#148 [BACK] Add prospect endpoint
  ram-back/src/controller/prospect.ts
  ram-back/src/controller/routes.ts
Labels: API, 🏕 Medium

#144 [BACK] Add Seeds for prospect 4701
  ram-back/src/seeds/index.ts
Labels: API, 🏝 Low

#133 M1 s10 tablas grupos
  ram-front/src/__test__/searchAgentTable.test.tsx
  ram-front/src/__test__/searchDeliveryTable.test.tsx
  ram-front/src/components/tables/SearchAgentRow.tsx
  ram-front/src/components/tables/SearchAgentTable.tsx
  ram-front/src/components/tables/SearchDeliveryRow.tsx
  ram-front/src/components/tables/SearchDeliveryTable.tsx
  ram-front/src/pages/Examples.tsx
  ram-front/src/types/index.ts
Labels: WEB, 🐂 Medium

#147 200 m1 s09 conectar boton
  ram-front/src/__test__/managerCourses.test.tsx
  ram-front/src/components/forms/ModalGroupForm.tsx
  ram-front/src/pages/ManagerGroups.tsx
Labels: enhancement, WEB, 🦔 Tiny

#159 [FRONT] Add form prospect and its test
  ram-back/src/app/prospect.ts
  ram-back/src/controller/prospect.ts
  ram-front/src/__test__/modalProspectForm.test.tsx
  ram-front/src/assets/css/index.css
  ram-front/src/components/forms/ModalGroupForm.tsx
  ram-front/src/components/forms/ModalProspectForm.tsx
  ram-front/src/pages/Prospects.tsx
  ram-front/src/pages/TODO/Prospects.tsx
  ram-front/src/routes/privates.tsx
Labels: WEB, 🐂 Medium

#153 150 back add new function that returns all the prospects and status
  ram-back/src/__tests__/app/prospect.test.ts
  ram-back/src/app/prospect.ts
Labels: API, 🏕 Medium

#162 158 front show validation errors in the create deliverable form
  ram-front/src/assets/css/index.css
  ram-front/src/components/forms/ModalDeliveryForm.tsx
  ram-front/src/pages/EditGroup.tsx
  ram-front/src/pages/Examples.tsx
Labels: 🐇 Small, 🏕 Medium

#168 [FRONT] Add conection FRONT and BACK for add prospect
  ram-back/src/__tests__/app/prospect.test.ts
  ram-back/src/app/status.ts
  ram-back/src/controller/routes.ts
  ram-back/src/controller/sale.ts
  ram-back/src/controller/status.ts
  ram-back/src/entities/status.entity.ts
  ram-back/src/seeds/index.ts
  ram-front/index.html
  ram-front/src/__test__/modalProspectForm.test.tsx
  ram-front/src/assets/css/index.css
  ram-front/src/components/deliverables/ListDeliverables.tsx
  ram-front/src/components/forms/ModalProspectForm.tsx
  ram-front/src/pages/Prospects.tsx
  ram-front/src/types/index.ts
  ram-front/tailwind.config.cjs
Labels: bug, API, WEB, 🦑 Large, 🐂 Medium

#156 138 m5 s05gerentever métricas de prospectos de un agente
  ram-back/src/__tests__/controller/prospect.test.tsx
  ram-back/src/controller/prospect.ts
  ram-back/src/controller/user.ts
  ram-back/src/seeds/index.ts
  ram-front/src/__test__/prospectsfunnel.test.tsx
  ram-front/src/components/prospects/FunnelRow.tsx
  ram-front/src/components/prospects/FunnelTable.tsx
  ram-front/src/lib/api/api-prospect.tsx
  ram-front/src/pages/ProspectsFunnel.tsx
  ram-front/src/routes/privates.tsx
  ram-front/src/types/index.ts
Labels: bug, 🐂 Medium, 🏔 High

#172 [BACK] Add endpoint and test from get prospects
  ram-back/src/app/prospect.ts
  ram-back/src/controller/prospect.ts
  ram-front/src/assets/css/index.css
Labels: API, 🏕 Medium

#186 M1 s12 2600 modify delivery endpoint
  ram-back/src/__tests__/app/sale.test.ts
  ram-back/src/app/sale.ts
Labels: WEB, 🐇 Small

#188 120 m1 s10administradormodificar o borrar un grupo de entregables
  ram-back/src/__tests__/controller/groups.test.ts
  ram-back/src/app/groups.ts
  ram-back/src/controller/group.ts
Labels: API

#167 [FRONT] connect Add group modal with endpoint
  ram-back/src/controller/group.ts
  ram-front/src/__test__/managerCourses.test.tsx
  ram-front/src/components/forms/ModalGroupForm.tsx
  ram-front/src/components/sales/CardNewSale.tsx
  ram-front/src/components/sales/VerifySalesTable.tsx
  ram-front/src/pages/ManagerGroups.tsx
  ram-front/src/types/index.ts
Labels: WEB, 🐂 Medium, 🏔 High

#199 [FRONT] redirect to edit group
  ram-front/src/pages/ManagerGroups.tsx
Labels: WEB, 🦔 Tiny, 🏔 High

#205 202 frontback connect front back of update modal
  ram-back/src/controller/sale.ts
  ram-back/src/seeds/index.ts
  ram-front/src/components/forms/SaleForm.tsx
  ram-front/src/components/sales/CardNewSale.tsx
  ram-front/src/components/sales/SalesRow.tsx
  ram-front/src/components/sales/SalesTable.tsx
  ram-front/src/pages/ModifySale.tsx
  ram-front/src/pages/NewSale.tsx
  ram-front/src/types/index.ts
Labels: enhancement, 🏕 Medium

#206 [FRONT] Added delete funcionality, warning and confirmation pop ups
  ram-front/src/components/tables/SearchDeliveryRow.tsx
Labels: WEB, 🐇 Small, 🏔 High

#211 207 back deliveries in groups arent shown to users
  ram-back/src/app/deliveries.ts
  ram-back/src/app/user-delivery.ts
  ram-back/src/controller/delivery.ts
  ram-back/src/controller/group.ts
Labels: bug

#213 [FRONT] Added re render when add or delete a delivery
  ram-front/src/__test__/searchDeliveryTable.test.tsx
  ram-front/src/components/tables/SearchAgentTable.tsx
  ram-front/src/components/tables/SearchDeliveryRow.tsx
  ram-front/src/components/tables/SearchDeliveryTable.tsx
  ram-front/src/pages/EditGroup.tsx
  ram-front/src/pages/Examples.tsx
Labels: bug

#215 [BACK][FRONT] Fix controller and view
  ram-back/src/controller/sale.ts
  ram-front/src/pages/Prospects.tsx
Labels: bug

#228 [FRONT] Added Button for editing the group in the group deliverables …
  ram-front/src/pages/ManagerGroup.tsx
Labels: WEB, 🐇 Small, 🏝 Low

#225 177 front add components for list prospects
  ram-back/src/__tests__/controller/prospects.test.ts
  ram-back/src/app/prospect.ts
  ram-front/src/__test__/modalProspectForm.test.tsx
  ram-front/src/components/forms/ModalProspectForm.tsx
  ram-front/src/components/prospects/ListProspects.tsx
  ram-front/src/components/prospects/RowProspect.tsx
  ram-front/src/pages/Examples.tsx
  ram-front/src/pages/Prospects.tsx
  ram-front/src/types/index.ts
Labels: WEB, 🏝 Low

#234 233 front hook for search filter
  ram-back/src/__tests__/controller/user.test.ts
  ram-back/src/controller/user.ts
  ram-back/src/seeds/index.ts
  ram-front/src/components/prospects/FunnelRow.tsx
  ram-front/src/components/prospects/FunnelTable.tsx
  ram-front/src/components/prospects/ListProspects.tsx
  ram-front/src/components/tables/SearchAgentRow.tsx
  ram-front/src/components/tables/SearchAgentTable.tsx
  ram-front/src/components/tables/SearchDeliveryRow.tsx
  ram-front/src/components/tables/SearchDeliveryTable.tsx
  ram-front/src/hooks/useSearch.ts
  ram-front/src/pages/EditGroup.tsx
  ram-front/src/pages/Prospects.tsx
Labels: WEB, 🐂 Medium

#243 [FRONT]Add front ProspectHistory ProspectListHistory
  ram-front/src/components/prospects/ProspectListHistory.tsx
  ram-front/src/pages/Examples.tsx
  ram-front/src/pages/ProspectsHistory.tsx
  ram-front/src/routes/privates.tsx
Labels: WEB, 🏕 Medium, 🌋 Urgent

#245 239 back add links to deliveries
  ram-back/src/__tests__/app/deliveries.test.ts
  ram-back/src/__tests__/controller/delivery.test.ts
  ram-back/src/app/deliveries.ts
  ram-back/src/controller/delivery.ts
  ram-back/src/entities/delivery-link.entity.ts
  ram-back/src/entities/delivery.entity.ts
  ram-back/src/entities/index.ts
  ram-back/src/seeds/index.ts
Labels: API, 🐂 Medium

#248 [FRONT] Added New Modal for creating users
  ram-back/src/app/user.ts
  ram-back/src/controller/user.ts
  ram-back/src/entities/columns.ts
  ram-back/src/entities/user.entity.ts
  ram-front/src/components/forms/ModalAddUser.tsx
  ram-front/src/types/index.ts
Labels: API, WEB

#242 [FRONT] Add delivery page
  ram-back/src/app/deliveries.ts
  ram-back/src/controller/delivery.ts
  ram-back/src/seeds/index.ts
  ram-front/src/__test__/linkDelivery.test.tsx
  ram-front/src/__test__/listDeliveries.test.tsx
  ram-front/src/components/Image.tsx
  ram-front/src/components/deliverables/DeliveryDescription.tsx
  ram-front/src/components/deliverables/LinkDelivery.tsx
  ram-front/src/components/deliverables/ListDeliverables.tsx
  ram-front/src/components/generics/cards/DeliveryCard.tsx
  ram-front/src/pages/DeliveryGroup.tsx
  ram-front/src/routes/privates.tsx
  ram-front/src/types/index.ts
Labels: WEB, 🏕 Medium

#256 [FRONT] [BACK] Resolved bugs and upload file correctly
  ram-back/src/app/deliveries.ts
  ram-back/src/controller/delivery.ts
  ram-front/src/components/deliverables/LinkDelivery.tsx
  ram-front/src/components/deliverables/ListManagerDeliveries.tsx
  ram-front/src/pages/DeliveryGroup.tsx
  ram-front/src/pages/Groups.tsx
  ram-front/src/pages/ManagerGroup.tsx
  ram-front/src/types/index.ts
Labels: bug, API, invalid, 🐂 Medium, 🏕 Medium

#247 247 front add tests prospect history
  ram-front/src/__test__/ProspectsHistory.test.tsx
  ram-front/src/components/prospects/ProspectHistoryTable.tsx
  ram-front/src/components/prospects/ProspectListHistory.tsx
  ram-front/src/pages/Examples.tsx
  ram-front/src/pages/ProspectsHistory.tsx
Labels: WEB, 🐇 Small, 🌋 Urgent

#269 258 front back add delivery description view for manager
  ram-back/src/app/deliveries.ts
  ram-back/src/controller/delivery.ts
  ram-back/src/entities/columns.ts
  ram-back/src/entities/delivery.entity.ts
  ram-front/src/components/deliverables/ListDeliverables.tsx
  ram-front/src/components/forms/EditDeliveryForm.tsx
  ram-front/src/components/generics/cards/DeliveryCard.tsx
  ram-front/src/components/tables/SearchDeliveryRow.tsx
  ram-front/src/pages/DeliveryGroup.tsx
  ram-front/src/pages/ManagerDeliveryGroup.tsx
  ram-front/src/routes/privates.tsx
  ram-front/src/types/index.ts
Labels: 🏔 High

#266 260 front test for delivery description
  ram-front/src/__test__/deliveryDescription.test.tsx
  ram-front/src/__test__/image.test.tsx
  ram-front/src/components/Image.tsx
  ram-front/src/components/deliverables/DeliveryDescription.tsx
Labels: API, 🦔 Tiny

#273 270 frontback edit profile and success message
  ram-back/src/__tests__/app/user.test.ts
  ram-back/src/controller/user.ts
  ram-front/src/components/forms/ProfileForm.tsx
  ram-front/src/components/generics/lists/LinkList.tsx
  ram-front/src/pages/Profile.tsx
Labels: 🏕 Medium

#274 268 back test modify profile
  ram-back/src/__tests__/controller/user.test.ts
  ram-front/src/assets/css/index.css
Labels: API

#278 271 front add links to deliveries
  ram-back/src/__tests__/app/links.test.ts
  ram-back/src/__tests__/controller/prospect.test.tsx
  ram-back/src/app/deliveries.ts
  ram-back/src/controller/delivery.ts
  ram-front/src/components/filters/DropdownFilter.tsx
  ram-front/src/components/forms/EditDeliveryForm.tsx
  ram-front/src/components/generics/lists/LinkDeliveryList.tsx
  ram-front/src/pages/ManagerDeliveryGroup.tsx
Labels: API, 🐂 Medium, 🏕 Medium

#277 5500 modal modificar prospecto
  ram-front/src/components/forms/ModalModifyStatusProspect.tsx
  ram-front/src/components/prospects/ListProspects.tsx
  ram-front/src/components/prospects/RowProspect.tsx
  ram-front/src/pages/Prospects.tsx
Labels: WEB, 🐂 Medium, 🏔 High

#276 [BACK] Function and endpoint to modify prospect
  ram-back/src/app/prospect.ts
  ram-back/src/controller/prospect.ts
Labels: API, 🐂 Medium, 🏔 High

#287 281 front bug when modifying or adding a prospectus it is not re rendered
  ram-back/src/controller/prospect.ts
  ram-front/src/components/forms/ModalModifyStatusProspect.tsx
  ram-front/src/components/prospects/ListProspects.tsx
  ram-front/src/components/prospects/RowProspect.tsx
  ram-front/src/pages/Examples.tsx
  ram-front/src/pages/ManageProspects.tsx
  ram-front/src/pages/Prospects.tsx
Labels: bug, API, 🐂 Medium, 🏔 High

#288 [FRONT][BACK] See profile, see my profile and member list
  ram-back/src/__tests__/controller/user.test.ts
  ram-back/src/app/user.ts
  ram-back/src/controller/user.ts
  ram-front/src/components/forms/ProfileForm.tsx
  ram-front/src/components/generics/cards/ProfileCard.tsx
  ram-front/src/components/generics/lists/LinkList.tsx
  ram-front/src/components/generics/lists/LinkRow.tsx
  ram-front/src/components/includes/NavBar/NavBar.tsx
  ram-front/src/components/members/RowMember.tsx
  ram-front/src/components/members/TableMembers.tsx
  ram-front/src/components/prospects/FunnelRow.tsx
  ram-front/src/components/prospects/FunnelTable.tsx
  ram-front/src/pages/Members.tsx
  ram-front/src/pages/MyProfile.tsx
  ram-front/src/pages/Profile.tsx
  ram-front/src/pages/ViewProfile.tsx
  ram-front/src/routes/privates.tsx
  ram-front/src/types/index.ts
Labels: 🦑 Large, 🏔 High

#290 M5 s07 endpoint estados de prospectos
  ram-back/src/app/satus-prospect.ts
  ram-back/src/controller/routes.ts
  ram-back/src/controller/status-prospect.ts
  ram-front/src/__test__/ProspectsHistory.test.tsx
  ram-front/src/components/prospects/ListProspects.tsx
  ram-front/src/components/prospects/ProspectHistoryTable.tsx
  ram-front/src/components/prospects/ProspectListHistory.tsx
  ram-front/src/components/prospects/RowProspect.tsx
  ram-front/src/pages/Examples.tsx
  ram-front/src/pages/ProspectsHistory.tsx
  ram-front/src/routes/privates.tsx
  ram-front/src/types/index.ts
Labels: WEB

#291 1808 add front filters to sales
  ram-back/src/controller/status-prospect.ts
  ram-back/src/seeds/index.ts
  ram-front/src/__test__/verifySales.test.tsx
  ram-front/src/components/sales/VerifySalesRow.tsx
  ram-front/src/components/sales/VerifySalesTable.tsx
  ram-front/src/pages/Examples.tsx
  ram-front/src/pages/VerifySales.tsx
Labels: enhancement

#286 279 back controller and function update profile tests
  ram-back/src/__tests__/app/user.test.ts
  ram-back/src/__tests__/controller/user.test.ts
Labels: API
